title: Vagelis Protopapas
logo: # picture
email: # email
description: Ph.D Candidate
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:

  - name: Research
    link: /research.html
  - name: Contact
    link: /contact.html
  - name: Cv
    link: https://mail-attachment.googleusercontent.com/attachment/u/0/?ui=2&ik=d216862c69&attid=0.1&permmsgid=msg-a:r503888277580759032&th=18eccec6056565f4&view=att&disp=inline&realattid=f_luv5rcbz0&saddbat=ANGjdJ-usQ7Gi4UtZ6hZwe2EKTQWmu5bM19PyLVgJgA2AnV1IxFlkANwjZBpytACYZw1EKRkpHBMTKpSweLDO8t2wSlaD0J7v1qzqwAME2wBIurOu8ml34eIaij1IDnXtHKMubLKKKzONMlcmpptWfOWBuM2y81w3W3LBvjqvgWTh-huMQmuhNtxAcyG1nyWfgP-mvdUxyqHVNB5DrZk8z3DGdJCOPiOrsUj40PLXtkuPezciTulQbv1DgCvqLFRYU2WUdHbNOyN9y9gqQTxjcPshoQV9-t8UMqLxlEY8Kc9vigBeJEXO-79uTtWHUmr2c3Aa9jgqkcLySxVYRfx0QJZf8TsODtUc_Ov5k6xP-RQcaqBxuUPzDQTnMfMYy0YQHMonzjBM6Z2v3wIM1CSpbRB9KcKJCCLOJWFxxezgj5i3vdfqcYALMPHls8zTdq3sfMSOOSEct0lwbzIPSdov4_83WM5i9bxFvK_KRgFog0MYdHX0S6BBPgfhXheSYU-ZiX9XrabmeJN0vC5iTHmbOa1IXq5SwtC-xpPH3bjABfLrwvANIii4BXTUnl8iJCR69t8EVzv1SeqBbuzhML36fLgPopY-kbfVrdGYM9OH2ID8UaRqizsY1i2lFVjojQynMYFicaTG27k0624E4hCcTBDXssLBodyP4lz13VNwAkKkjTDXw2Hqv_hhdscKHZvswTU4BcyZAJd_6Dc_wMkCMf9OudRtLu6ELu93ma7uSlibP1VGzz3Z2-ZraPboIndll22QhNIQjJDx4g4pHaKrLHmqzwM2FYQIghMZPNwoU_4GAREreCBZMaS0LCwjjXTwOA-AaVurkTQezPVW2kEYQS85tlqeNoo0ng-DmadK2UrZHlv2EDlopxjUhZ-3jr50uqxXkKcMss4zgd_LjpPEvAJSEhE0u_WyVrB7QVF4JENX7g-MXVi1goMwHZFr_XZ71qzUQHe4h6z4506z7w166YQHUyJwVkB8Pao14Dg1o20U_kGGJLdQEujJuK5cNxXNKUKiwQJRoeM0XDahqcEdMuvsgbyT34-eieuk4OMaw
    
#  - name: Google Scholar
#    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
#    link: https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AKKJWFdLfVaCMyAOqbtady7_kOXwFC_yuQwZ7j--9reCTKbUXfqc58MMsh2LYA_mxAgMfVTrdpxu0AgnKGpJUw&user=rQIYIgMAAAAJ
#  - name: Blog
#   icon: <i class="fa-solid fa-pen"></i>
#    link: https://www.bodunhu.com/blog/
#  - name: Project Repository
#    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
 #   link: https://github.com/BDHU/minimalist

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
